apiVersion: v1
kind: Secret
metadata:
  name: devops-microservice-secret
  namespace: devops-microservice
  labels:
    app: devops-microservice
    component: secret
type: Opaque
data:
  # JWT_SECRET_KEY base64 encoded
  # To generate: echo -n "your-super-secret-jwt-key-for-production" | base64
  # This is a placeholder - replace with actual secret in production
  JWT_SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1mb3ItcHJvZHVjdGlvbg==
---
# Alternative: Use stringData for easier management (Kubernetes will encode automatically)
apiVersion: v1
kind: Secret
metadata:
  name: devops-microservice-secret-alt
  namespace: devops-microservice
  labels:
    app: devops-microservice
    component: secret-alt
type: Opaque
stringData:
  JWT_SECRET_KEY: "change-this-in-production-use-strong-secret-key-256bits"