apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-microservice-config
  namespace: devops-microservice
  labels:
    app: devops-microservice
    component: config
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  
  # Python Configuration
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  
  # API Configuration
  API_KEY: "2f5ae96c-b558-4c7b-a590-a501ae1c3f6c"
  ALGORITHM: "HS256"
  TOKEN_EXPIRY_HOURS: "1"
  
  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"
  
  # Monitoring
  METRICS_ENABLED: "true"
  
  # Application Metadata
  APP_NAME: "DevOps Microservice"
  APP_VERSION: "1.0.0"